- type: department
  id: Taipan
  name: department-Taipan
  description: department-Taipan-description
  color: "#D381C9"
  roles:
  - TaipanAtmosphericsEngineer
  - TaipanBotanist
  - TaipanCargotech
  - TaipanChef
  - TaipanCommunicationsOfficer
  - TaipanMedic
  - TaipanParamedic
  - TaipanRecruit
  - TaipanResearchDirector
  - TaipanResearcher
  - TaipanTechnician
  - TaipanTechnicalOperationsSupervisor
  editorHidden: true

- type: department
  id: NKVB
  name: department-NKVB
  description: department-NKVB-description
  color: "#ad4040"
  roles:
  - Politkom
  - Politruk
